plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Gemfile'

# Gem layout
Gemspec/DevelopmentDependencies:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'lib/ooxl/ooxl.rb'

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 13

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Layout
Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Layout/EndOfLine:
  Enabled: false

# Naming
Naming/MethodParameterName:
  AllowedNames:
    - id
    - b

Naming/VariableNumber:
  Enabled: false

# RSpec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false
